FROM ubuntu:latest

RUN ["echo", "-e", "GitBranch: $SOURCE_BRANCH \nGitCommit: $SOURCE_COMMIT \nDockerImage: $IMAGE_NAME "] > DOCKER_IMAGE_INFO
# RUN echo -e "GitBranch: $SOURCE_BRANCH \nGitCommit: $SOURCE_COMMIT \nDockerImage: $IMAGE_NAME " > DOCKER_IMAGE_INFO
