repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.2.2
  hooks:
    - id: pyupgrade
      args:
        - --py37-plus
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
      args:
        - --unsafe
    - id: check-ast
    - id: detect-private-key
    - id: check-added-large-files
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args:
        - --profile=black
        - --skip-glob=wandb/**/*
        - --thirdparty=wandb
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      args:
        - --line-length=120
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: flake8
      args:
        - --ignore=E501 W503 E203
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
    - id: mypy
      args:
        - --no-strict-optional
        - --ignore-missing-imports
- repo: https://github.com/python-poetry/poetry
  rev: 1.3.1
  hooks:
    - id: poetry-export
      name: poetry-export requirements.txt
      args: ["--without-hashes", "--without-urls", "-o", "requirements/requirements.txt", "-E", "torch", "-E", "atari", "-E", "mujoco"]
    - id: poetry-export
      name: poetry-export requirements-torch.txt
      args: ["--without-hashes", "--without-urls", "-o", "requirements/requirements-torch.txt", "-E", "torch", "-E", "atari", "-E", "mujoco"]
    - id: poetry-export
      name: poetry-export requirements-dev.txt
      args: ["--without-hashes", "--without-urls", "-o", "requirements/requirements-dev.txt", "-E", "torch", "-E", "atari", "-E", "mujoco", "-E", "dev"]
    - id: poetry-export
      name: poetry-export requirements-torch-dev.txt
      args: ["--without-hashes", "--without-urls", "-o", "requirements/requirements-torch-dev.txt", "-E", "torch", "-E", "atari", "-E", "mujoco", "-E", "dev"]
    - id: poetry-export
      name: poetry-export requirements-torch-atari.txt
      args: ["--without-hashes", "--without-urls", "-o", "requirements/requirements-torch-atari.txt", "-E", "torch", "-E", "atari"]
    - id: poetry-export
      name: poetry-export requirements-torch-atari-dev.txt
      args: ["--without-hashes", "--without-urls", "-o", "requirements/requirements-torch-atari-dev.txt", "-E", "torch", "-E", "atari", "-E", "dev"]
    - id: poetry-export
      name: poetry-export requirements-torch-mujoco.txt
      args: ["--without-hashes", "--without-urls", "-o", "requirements/requirements-torch-mujoco.txt", "-E", "torch", "-E", "mujoco"]
    - id: poetry-export
      name: poetry-export requirements-torch-mujoco-dev.txt
      args: ["--without-hashes", "--without-urls", "-o", "requirements/requirements-torch-mujoco-dev.txt", "-E", "torch", "-E", "mujoco", "-E", "dev"]
