repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.2.2
  hooks:
    - id: pyupgrade
      args:
        - --py37-plus
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
    args: ['--unsafe']
  - id: check-ast
  - id: detect-private-key
  - id: check-added-large-files
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args:
        - --profile=black
        - --skip-glob=wandb/**/*
        - --thirdparty=wandb
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      args:
        - --line-length=120
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: flake8
      args:
        - --ignore=E501 W503 E128 E203 F401 F403
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
    - id: mypy
      args: [--no-strict-optional, --ignore-missing-imports]
