[dqn]

CartPole-v1 = """
    python abcdrl/dqn.py \
        --num-envs 1 \
        --eval-frequency 1000 \
        --num-steps-eval 100 \
        --total-timesteps 500000 \
        --gamma 0.99 \
        --buffer-size 10000 \
        --start-epsilon 1.0 \
        --end-epsilon 0.05 \
        --exploration-fraction 0.5 \
        --batch-size 128 \
        --learning-rate 2.5e-4 \
        --learning-starts 10000 \
        --target-network-frequency 500 \
        --train-frequency 10 \
"""


[ddqn]

CartPole-v1 = """
    python abcdrl/ddqn.py \
        --num-envs 1 \
        --eval-frequency 1000 \
        --num-steps-eval 100 \
        --total-timesteps 500000 \
        --gamma 0.99 \
        --buffer-size 10000 \
        --start-epsilon 1.0 \
        --end-epsilon 0.05 \
        --exploration-fraction 0.5 \
        --batch-size 128 \
        --learning-rate 2.5e-4 \
        --learning-starts 10000 \
        --target-network-frequency 500 \
        --train-frequency 10 \
"""


[pdqn]
CartPole-v1 = """
    python abcdrl/pdqn.py \
        --num-envs 1 \
        --eval-frequency 1000 \
        --num-steps-eval 100 \
        --total-timesteps 500000 \
        --gamma 0.99 \
        --alpha 0.2 \
        --beta 0.6 \
        --buffer-size 10000 \
        --start-epsilon 1.0 \
        --end-epsilon 0.05 \
        --exploration-fraction 0.5 \
        --batch-size 128 \
        --learning-rate 2.5e-4 \
        --learning-starts 10000 \
        --target-network-frequency 500 \
        --train-frequency 10 \
"""
