[dqn]

CartPole-v1 = """
    python abcdrl/dqn.py \
        --env-id CartPole-v1 \
        --num-envs 1 \
        --total-timesteps 500000 \
        --gamma 0.99 \
        --buffer-size 10000 \
        --start-epsilon 1.0 \
        --end-epsilon 0.05 \
        --exploration-fraction 0.5 \
        --batch-size 128 \
        --learning-rate 2.5e-4 \
        --learning-starts 10000 \
        --target-network-frequency 500 \
        --train-frequency 10 \
"""

Acrobot-v1 = """
    python abcdrl/dqn.py \
        --env-id Acrobot-v1 \
        --num-envs 1 \
        --total-timesteps 500000 \
        --gamma 0.99 \
        --buffer-size 10000 \
        --start-epsilon 1.0 \
        --end-epsilon 0.05 \
        --exploration-fraction 0.2 \
        --batch-size 128 \
        --learning-rate 2.5e-4 \
        --learning-starts 1000 \
        --target-network-frequency 500 \
        --train-frequency 4 \
"""

MountainCar-v0 = """
    python abcdrl/dqn.py \
        --env-id MountainCar-v0 \
        --num-envs 1 \
        --total-timesteps 500000 \
        --gamma 0.98 \
        --buffer-size 10000 \
        --start-epsilon 1.0 \
        --end-epsilon 0.05 \
        --exploration-fraction 0.5 \
        --batch-size 128 \
        --learning-rate 2e-3 \
        --learning-starts 10000 \
        --target-network-frequency 800 \
        --train-frequency 4 \
"""


BreakoutNoFrameskip-v4 = """
    python abcdrl/dqn_atari.py \
        --env-id BreakoutNoFrameskip-v4 \
        --num-envs 1 \
        --total-timesteps 10000000 \
        --gamma 0.99 \
        --buffer-size 1000000 \
        --start-epsilon 1.0 \
        --end-epsilon 0.01 \
        --exploration-fraction 0.1 \
        --batch-size 32 \
        --learning-rate 1e-4 \
        --learning-starts 50000 \
        --target-network-frequency 1000 \
        --train-frequency 4 \
"""

PongNoFrameskip-v4 = """
    python abcdrl/dqn_atari.py \
        --env-id PongNoFrameskip-v4 \
        --num-envs 1 \
        --total-timesteps 10000000 \
        --gamma 0.99 \
        --buffer-size 1000000 \
        --start-epsilon 1.0 \
        --end-epsilon 0.01 \
        --exploration-fraction 0.1 \
        --batch-size 32 \
        --learning-rate 1e-4 \
        --learning-starts 50000 \
        --target-network-frequency 1000 \
        --train-frequency 4 \
"""

BeamRiderNoFrameskip-v4 = """
    python abcdrl/dqn_atari.py \
        --env-id BeamRiderNoFrameskip-v4 \
        --num-envs 1 \
        --total-timesteps 10000000 \
        --gamma 0.99 \
        --buffer-size 1000000 \
        --start-epsilon 1.0 \
        --end-epsilon 0.01 \
        --exploration-fraction 0.1 \
        --batch-size 32 \
        --learning-rate 1e-4 \
        --learning-starts 50000 \
        --target-network-frequency 1000 \
        --train-frequency 4 \
"""


[ddqn]

CartPole-v1 = """
    python abcdrl/ddqn.py \
        --env-id CartPole-v1 \
        --num-envs 1 \
        --total-timesteps 500000 \
        --gamma 0.99 \
        --buffer-size 10000 \
        --start-epsilon 1.0 \
        --end-epsilon 0.05 \
        --exploration-fraction 0.5 \
        --batch-size 128 \
        --learning-rate 2.5e-4 \
        --learning-starts 10000 \
        --target-network-frequency 500 \
        --train-frequency 10 \
"""

Acrobot-v1 = """
    python abcdrl/ddqn.py \
        --env-id Acrobot-v1 \
        --num-envs 1 \
        --total-timesteps 500000 \
        --gamma 0.99 \
        --buffer-size 10000 \
        --start-epsilon 1.0 \
        --end-epsilon 0.05 \
        --exploration-fraction 0.2 \
        --batch-size 128 \
        --learning-rate 2.5e-4 \
        --learning-starts 1000 \
        --target-network-frequency 500 \
        --train-frequency 4 \
"""

MountainCar-v0 = """
    python abcdrl/ddqn.py \
        --env-id MountainCar-v0 \
        --num-envs 1 \
        --total-timesteps 500000 \
        --gamma 0.98 \
        --buffer-size 10000 \
        --start-epsilon 1.0 \
        --end-epsilon 0.05 \
        --exploration-fraction 0.5 \
        --batch-size 128 \
        --learning-rate 2e-3 \
        --learning-starts 10000 \
        --target-network-frequency 800 \
        --train-frequency 4 \
"""


[pdqn]

CartPole-v1 = """
    python abcdrl/pdqn.py \
        --env-id CartPole-v1 \
        --num-envs 1 \
        --total-timesteps 500000 \
        --gamma 0.99 \
        --alpha 0.2 \
        --beta 0.6 \
        --buffer-size 10000 \
        --start-epsilon 1.0 \
        --end-epsilon 0.05 \
        --exploration-fraction 0.5 \
        --batch-size 128 \
        --learning-rate 2.5e-4 \
        --learning-starts 10000 \
        --target-network-frequency 500 \
        --train-frequency 10 \
"""

Acrobot-v1 = """
    python abcdrl/pdqn.py \
        --env-id Acrobot-v1 \
        --num-envs 1 \
        --total-timesteps 500000 \
        --gamma 0.99 \
        --alpha 0.2 \
        --beta 0.6 \
        --buffer-size 10000 \
        --start-epsilon 1.0 \
        --end-epsilon 0.05 \
        --exploration-fraction 0.2 \
        --batch-size 128 \
        --learning-rate 2.5e-4 \
        --learning-starts 1000 \
        --target-network-frequency 500 \
        --train-frequency 4 \
"""

MountainCar-v0 = """
    python abcdrl/pdqn.py \
        --env-id MountainCar-v0 \
        --num-envs 1 \
        --total-timesteps 500000 \
        --gamma 0.98 \
        --alpha 0.2 \
        --beta 0.6 \
        --buffer-size 10000 \
        --start-epsilon 1.0 \
        --end-epsilon 0.05 \
        --exploration-fraction 0.5 \
        --batch-size 128 \
        --learning-rate 2e-3 \
        --learning-starts 10000 \
        --target-network-frequency 800 \
        --train-frequency 4 \
"""


[ddpg]

Hopper-v4 = """
    python abcdrl/ddpg.py \
        --env-id Hopper-v4 \
        --num-envs 1 \
        --total-timesteps 1000000 \
        --gamma 0.99 \
        --buffer-size 1000000 \
        --exploration-noise 0.1 \
        --batch-size 256 \
        --learning-rate 3e-4 \
        --tau 0.005 \
        --learning-starts 25000 \
        --train-frequency 1 \
        --policy-frequency 2 \
"""

Walker2d-v4 = """
    python abcdrl/ddpg.py \
        --env-id Walker2d-v4 \
        --num-envs 1 \
        --total-timesteps 1000000 \
        --gamma 0.99 \
        --buffer-size 1000000 \
        --exploration-noise 0.1 \
        --batch-size 256 \
        --learning-rate 3e-4 \
        --tau 0.005 \
        --learning-starts 25000 \
        --train-frequency 1 \
        --policy-frequency 2 \
"""

HalfCheetah-v4 = """
    python abcdrl/ddpg.py \
        --env-id HalfCheetah-v4 \
        --num-envs 1 \
        --total-timesteps 1000000 \
        --gamma 0.99 \
        --buffer-size 1000000 \
        --exploration-noise 0.1 \
        --batch-size 256 \
        --learning-rate 3e-4 \
        --tau 0.005 \
        --learning-starts 25000 \
        --train-frequency 1 \
        --policy-frequency 2 \
"""

[td3]


Hopper-v4 = """
    python abcdrl/td3.py \
        --env-id Hopper-v4 \
        --num-envs 1 \
        --total-timesteps 1000000 \
        --gamma 0.99 \
        --buffer-size 1000000 \
        --exploration-noise 0.1 \
        --noise-clip 0.5 \
        --batch-size 256 \
        --learning-rate 3e-4 \
        --tau 0.005 \
        --policy-noise 0.2 \
        --learning-starts 25000 \
        --train-frequency 1 \
        --policy-frequency 2 \
"""

Walker2d-v4 = """
    python abcdrl/td3.py \
        --env-id Walker2d-v4 \
        --num-envs 1 \
        --total-timesteps 1000000 \
        --gamma 0.99 \
        --buffer-size 1000000 \
        --exploration-noise 0.1 \
        --noise-clip 0.5 \
        --batch-size 256 \
        --learning-rate 3e-4 \
        --tau 0.005 \
        --policy-noise 0.2 \
        --learning-starts 25000 \
        --train-frequency 1 \
        --policy-frequency 2 \
"""

HalfCheetah-v4 = """
    python abcdrl/td3.py \
        --env-id HalfCheetah-v4 \
        --num-envs 1 \
        --total-timesteps 1000000 \
        --gamma 0.99 \
        --buffer-size 1000000 \
        --exploration-noise 0.1 \
        --noise-clip 0.5 \
        --batch-size 256 \
        --learning-rate 3e-4 \
        --tau 0.005 \
        --policy-noise 0.2 \
        --learning-starts 25000 \
        --train-frequency 1 \
        --policy-frequency 2 \
"""


[sac]

Hopper-v4 = """
    python abcdrl/sac.py \
        --env-id Hopper-v4 \
        --num-envs 1 \
        --total-timesteps 1000000 \
        --gamma 0.99 \
        --buffer-size 1000000 \
        --exploration-noise 0.1 \
        --batch-size 256 \
        --q-lr 1e-3 \
        --policy-lr 3e-4 \
        --tau 0.005 \
        --alpha 0.2 \
        --autotune True \
        --learning-starts 25000 \
        --train-frequency 1 \
        --policy-frequency 2 \
        --target-network-frequency \
"""

Walker2d-v4 = """
    python abcdrl/sac.py \
        --env-id Walker2d-v4 \
        --num-envs 1 \
        --total-timesteps 1000000 \
        --gamma 0.99 \
        --buffer-size 1000000 \
        --exploration-noise 0.1 \
        --batch-size 256 \
        --q-lr 1e-3 \
        --policy-lr 3e-4 \
        --tau 0.005 \
        --alpha 0.2 \
        --autotune True \
        --learning-starts 25000 \
        --train-frequency 1 \
        --policy-frequency 2 \
        --target-network-frequency \
"""

HalfCheetah-v4 = """
    python abcdrl/sac.py \
        --env-id HalfCheetah-v4 \
        --num-envs 1 \
        --total-timesteps 1000000 \
        --gamma 0.99 \
        --buffer-size 1000000 \
        --exploration-noise 0.1 \
        --batch-size 256 \
        --q-lr 1e-3 \
        --policy-lr 3e-4 \
        --tau 0.005 \
        --alpha 0.2 \
        --autotune True \
        --learning-starts 25000 \
        --train-frequency 1 \
        --policy-frequency 2 \
        --target-network-frequency \
"""


[ppo]

Hopper-v4 = """
    python abcdrl/ppo.py \
        --env-id Hopper-v4 \
        --num-envs 1 \
        --total-timesteps 1000000 \
        --gamma 0.99 \
        --num-steps 2048 \
        --learning-rate 3e-4 \
        --anneal-lr True \
        --update-epochs 10 \
        --norm-adv True \
        --clip-coef 0.2 \
        --clip-vloss True \
        --ent-coef 0.0 \
        --vf-coef 0.5 \
        --max-grad-norm 0.5 \
        --num-minibatches 32 \
        --gae-lambda 0.95 \
"""

Walker2d-v4 = """
    python abcdrl/ppo.py \
        --env-id Walker2d-v4 \
        --num-envs 1 \
        --total-timesteps 1000000 \
        --gamma 0.99 \
        --num-steps 2048 \
        --learning-rate 3e-4 \
        --anneal-lr True \
        --update-epochs 10 \
        --norm-adv True \
        --clip-coef 0.2 \
        --clip-vloss True \
        --ent-coef 0.0 \
        --vf-coef 0.5 \
        --max-grad-norm 0.5 \
        --num-minibatches 32 \
        --gae-lambda 0.95 \
"""

HalfCheetah-v4 = """
    python abcdrl/ppo.py \
        --env-id HalfCheetah-v4 \
        --num-envs 1 \
        --total-timesteps 1000000 \
        --gamma 0.99 \
        --num-steps 2048 \
        --learning-rate 3e-4 \
        --anneal-lr True \
        --update-epochs 10 \
        --norm-adv True \
        --clip-coef 0.2 \
        --clip-vloss True \
        --ent-coef 0.0 \
        --vf-coef 0.5 \
        --max-grad-norm 0.5 \
        --num-minibatches 32 \
        --gae-lambda 0.95 \
"""
