version: 2.1

jobs:
  pytest-py310:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements/requirements-dev.txt
            sudo apt-get update
            sudo apt-get -y install wget unzip software-properties-common \
              libgl1-mesa-dev \
              libgl1-mesa-glx \
              libglew-dev \
              libosmesa6-dev patchelf swig
      - run:
          name: "test_codes_consistency"
          command: pytest tests/test_codes_consistency.py
      - run:
          name: "test_classic_control"
          command: pytest tests/test_classic_control.py
      - run:
          name: "test_mujoco"
          command: pytest tests/test_mujoco.py
      - run:
          name: "test_utils"
          command: pytest tests/test_utils.py

  pytest-py39:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements/requirements-dev.txt
            sudo apt-get update
            sudo apt-get -y install wget unzip software-properties-common \
              libgl1-mesa-dev \
              libgl1-mesa-glx \
              libglew-dev \
              libosmesa6-dev patchelf swig
      - run:
          name: "test_codes_consistency"
          command: pytest tests/test_codes_consistency.py
      - run:
          name: "test_classic_control"
          command: pytest tests/test_classic_control.py
      - run:
          name: "test_mujoco"
          command: pytest tests/test_mujoco.py
      - run:
          name: "test_utils"
          command: pytest tests/test_utils.py


  pytest-py38:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements/requirements-dev.txt
            sudo apt-get update
            sudo apt-get -y install wget unzip software-properties-common \
              libgl1-mesa-dev \
              libgl1-mesa-glx \
              libglew-dev \
              libosmesa6-dev patchelf swig
      - run:
          name: "test_codes_consistency"
          command: pytest tests/test_codes_consistency.py
      - run:
          name: "test_classic_control"
          command: pytest tests/test_classic_control.py
      - run:
          name: "test_mujoco"
          command: pytest tests/test_mujoco.py
      - run:
          name: "test_utils"
          command: pytest tests/test_utils.py


workflows:
  pytest-workflow:
    jobs:
      - pytest-py310
      - pytest-py39
      - pytest-py38
