name: "📚 Documentation"
description: Report an issue related to abcdRL documentation
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks :heart: for taking the time to fill out this report!**

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what should be improved in the documentation.
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have checked that there is no similar [issue](https://github.com/sdpkjc/abcdrl/issues) in the repo
          required: true
        - label: I have read the [documentation](https://docs.abcdrl.xyz)
          required: true
