name: mkdocs deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install mkdocs mkdocs-material mkdocs-static-i18n
      - run: mkdocs gh-deploy --force --clean --verbose
