name: pytest
on:
  push:
    paths-ignore:
      - 'docs/**/*'
      - '**/README.*'
      - 'LICENSE'
      - 'mkdocs.yml'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - 'CITATION.cff'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-22.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y install wget unzip \
            git software-properties-common \
            libgl1-mesa-dev \
            libgl1-mesa-glx \
            libglew-dev \
            libosmesa6-dev patchelf swig
      - name: Install macos dependencies
        if: runner.os == 'macOS'
        run: |
          brew install gcc@9
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-dev.txt
      - name: Test with pytest
        run: pytest --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
